org: svengerlach
app: tic-tac-toe-api
# Source: https://docs.nestjs.com/faq/serverless

service: tic-tac-toe-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  deploymentMethod: direct
  stage: ${opt:stage, self:custom.defaultStage}
  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}

custom:
  defaultStage: ${env:DOPPLER_ENVIRONMENT}

functions:
  main:
    handler: dist/main.handler
    environment:
      CORS_ORIGIN: ${env:CORS_ORIGIN}
      JWT_SECRET: ${env:JWT_SECRET}
      MONGO_URI: ${env:MONGO_URI}
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'